### ISSUE TITLE
SQL dump file contains extra objects

### ISSUE THREAD

**Issue by abollini** [DSpace-Labs/AIP-Files#1]
Looking to the sql file in https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data  I noted the following:
- there is an affiliation_seq object that is not part of the official dspace database schema
- the sql assign the ownership to the dspace user, it would be better to avoid this step so that a different user can be used without getting errors during the restore or eventually hit a collision (if the dspace user exists for other purpose)

**Comment by tdonohue** [comment]
Closing as fixed.

* The *first* issue (`affiliation_seq`) wasfixed in the new Entities data dump (https://github.com/DSpace-Labs/AIP-Files/releases/download/demo-entities-data/dspace7-entities-2021-04-14.sql).  See https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data
* After some looking around, I've decided **not to fix** the second issue.  It seems like most people recommend:
     * Always doing `pg_dump` with all ownership/permissions included
     * However, if you need to change ownership/permissions in the restore, use `pg_restore --no-owner` and similar.  See for example https://stackoverflow.com/a/31470664/3750035 and also https://stackoverflow.com/a/57748887/3750035
     * If this becomes problematic later on we can always rethink this.  However, for now, it seems like we can ask folks to use `pg_restore --no-owner` if they want to restore this content to a different owner/user.
